### ISSUE TITLE
Bad link to SDLvncviewer.c

### ISSUE THREAD

**Issue by willbprog127** [LibVNC/LibVNC.github.io#2]
On the following page, there is a link to the SDLvncviewer.c example, however it's 404 when clicked:
`https://libvnc.github.io/doc/html/libvncclient_doc.html`

The link that it points to is
`https://libvnc.github.io/doc/html/_s_d_lvncviewer_8c.html`

Thanks! :-)

**Comment by bk138** [comment]
Thanks for reporting! The docs are auto-generated by doxygen and the file in question is rfb/rfbclient.h, line 665. TBH, I don't know how to fix this. Care to help and research?

**Comment by willbprog127** [comment]
Thanks for that.  I cloned and tested locally and all of the links work fine for SDLvncviewer...?
