### ISSUE TITLE
My project use the library. https://github.com/KangLin/RabbitRemoteControl

### ISSUE THREAD

**Issue by KangLin** [LibVNC/LibVNC.github.io#5]
My project use the library. https://github.com/KangLin/RabbitRemoteControl

**Comment by bk138** [comment]
Hi! What info are you trying to get across?

**Comment by dscho** [comment]
> Hi! What info are you trying to get across?

My _guess_ is that @KangLin wanted to have their project listed at https://libvnc.github.io/#projects-using, in which case a PR to edit [the section](https://github.com/LibVNC/LibVNC.github.io/blob/b4f36701f791407726cf33e08a298b3500263725/index.html#L103-L146) would be more appropriate, methinks.

Having said that, this part of that project's [`README.md`](https://github.com/KangLin/RabbitRemoteControl#introduction) makes me think that it would be unwise to advertise it yet:

> I have no devices so I did not compile and test. Please test by yourself if you have devices. [...]

**Comment by bk138** [comment]
@KangLin please provide a PR when you think your project is ready for production use.
