### ISSUE TITLE
Add AVNC to the projects using page

### ISSUE THREAD

**Issue by user8446** [LibVNC/LibVNC.github.io#7]
Hi,

Just a note that https://github.com/gujjwal00/avnc uses LibVNCClient as is an excellent Android VNC client. It would be a great addition to the list.

Thank you

**Comment by bk138** [comment]
Very true. Do you want to create a pull request?

**Comment by user8446** [comment]
No problem, I'll get to it

**Comment by user8446** [comment]
https://github.com/LibVNC/LibVNC.github.io/pull/8#event-8079812714
